/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: pudry <marvin@42lausanne.ch>               +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/06/24 13:28:43 by pudry             #+#    #+#             */
/*   Updated: 2023/06/28 15:07:25 by pudry            ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdlib.h>
#include <unistd.h>

int		ft_check_input_nbr(char *cnbr);
int		ft_check_input_zero(char *str);
int		ft_strlen(char	*str);
int		ft_array_len(char *str, int i);
char	*ft_read_dic(char cnbr, char *ctype, char *file_name);
char	*ft_add_o_str(char *str);
char	*ft_add_twoo_str(char *str);
char	*ft_add_treeo_str(char *str);
char	*ft_restart_ctype(char *str);
char	*ft_generate_ctype(void);
void	ft_error_prog(void);
void	ft_put_array(char **str);
void	ft_error_dict(void);

/*This function will check if we have some null value in the array.
 * if is it the case, it s because we have an dictionary value.
 * So we have to return an error. if it is n t the case. we
 * call the function for writting the array*/
int	ft_check_array(char **array)
{
	int	i;
	int	j;

	i = 0;
	j = 0;
	while (array[i])
	{
		if (!array[i][j])
		{
			ft_error_dict();
			return (0);
		}
		i ++;
	}
	ft_put_array(array);
	return (0);
}

void	ft_set_values_initiales(char **ctype, char **ctypeo)
{
	*ctype = ft_generate_ctype();
	*ctypeo = ft_generate_ctype();
}

/*This function convert the number to an array of word*/
void	ft_nb_to_word(char *str, char *str_dico_name, char **array, int iasize)
{
	char	*ctype;
	char	*ctypeo;
	int		istr;

	ft_set_values_initiales(&ctype, &ctypeo);
	istr = ft_strlen(str) - 1;
	while (istr >= 0)
	{
		if (ft_strlen(ctype) == 1 && str[istr - 1] == '1')
		{
			array[iasize ++] = ft_read_dic(str[istr], "2", str_dico_name);
			istr -= 2;
			ctype = ft_add_o_str(ctype);
		}
		else if (str[istr --] != '0')
			array[iasize ++] = ft_read_dic(str[istr + 1], ctype, str_dico_name);
		ctype = ft_add_o_str(ctype);
		if (ft_strlen(ctype) == 4 && istr >= 0)
		{
			ctype = ft_restart_ctype(ctype);
			ctypeo = ft_add_treeo_str(ctypeo);
			array[iasize ++] = ft_read_dic('0', ctypeo, str_dico_name);
		}
	}
	ft_check_array(array);
}

/*This function will generate an array and print them.
 * The array is generated by the char number given in put.
 * And they convert them to word the conversion is made by the function
 * ft_read_dico(). She take tree  element. the charactere the int value
 * and the filename for the dictionary.
 * The int value is used for said if we want a thousand, a hundred, ...
 * For the specific case between 10 and 19, we use the function like an
 * unite but we put the number 2 on input of the function.*/
void	ft_array_conv(char *str, char *str_dico_name)
{
	int		iasize;
	char	**array;
	int		i;

	i = 0;
	iasize = ft_array_len(str, i) + 1;
	array = malloc(sizeof(*array) * iasize --);
	array[iasize] = 0;
	iasize = 0;
	if (ft_check_input_zero(str) == 1)
	{
		write(1, "zero\n", 5);
	}
	else
	{
		while (*str == '0')
			str ++;
		ft_nb_to_word(str, str_dico_name, array, iasize);
	}
}

/*The main function check if the input are correct and give the right 
 * argument to the function for converting the number to word.*/
int	main(int arg_n, char **arg_v)
{
	char	*str_dico_name;

	str_dico_name = malloc(sizeof(char) * 13);
	str_dico_name = "numbers.dict\0";
	if (arg_n == 2 && ft_check_input_nbr(arg_v[1]) == 1)
	{
		ft_array_conv(arg_v[1], str_dico_name);
	}
	else if (arg_n == 3 && ft_check_input_nbr(arg_v[2]) == 1 && *arg_v[1])
	{
		ft_array_conv(arg_v[2], arg_v[1]);
	}
	else
		ft_error_prog();
	return (0);
}
