# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cduffaut <marvin@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/06/25 23:12:07 by cduffaut          #+#    #+#              #
#    Updated: 2023/06/26 15:38:03 by pudry            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wall -Wextra -Werror check_input.c	ft_error.c	ft_get_strs.c	ft_util.c	main.c ft_append2.c	ft_find_line.c	ft_read_dic.c	ft_util2.c -o rush-02

fclean:
	rm -rf rush-02

